### ISSUE TITLE
Build new maps!

### ISSUE THREAD

**Issue by SpadesNeil** [TheReeplex/PrisonStation#2]
Post any possible inspiration material below.

**Comment by SpadesNeil** [comment]
Possible inspiration
![prison ship](https://cloud.githubusercontent.com/assets/6484985/18463463/5eafd4ae-7958-11e6-8b6f-1af2cddd09b9.jpg)

**Comment by OmniSyzygy** [comment]
ns2_jambi (From Natural Selection 2)

![image](https://cloud.githubusercontent.com/assets/4283883/18613377/63da16c2-7d2e-11e6-8653-2dd05ea28765.png)

ns2_prison

![image](https://cloud.githubusercontent.com/assets/4283883/18613391/b2465c80-7d2e-11e6-9d7e-7e7c37f705ca.png)

ns2_nothing

![image](https://cloud.githubusercontent.com/assets/4283883/18613398/cb720286-7d2e-11e6-91e4-f48127eb3a83.png)

ns2_goliath

![image](https://cloud.githubusercontent.com/assets/4283883/18613405/ec193ce8-7d2e-11e6-87d0-33c698ecc1d6.png)

**Comment by SpadesNeil** [comment]
![20160922180121_1](https://cloud.githubusercontent.com/assets/6484985/18770194/8bee1006-8101-11e6-8f5b-f4c5a361d587.jpg)
